### ISSUE TITLE
Deprecation warning with node 7.0.0

### ISSUE THREAD

**Issue by asprouse** [archiverjs/node-compress-commons#22]
```
(node:11485) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
```
Found this when tracing https://github.com/archiverjs/node-archiver/issues/204. It seems to be coming from an outdated version of buffer-crc32. This project uses 0.2.1 and the warning was fixed in 0.2.7

**Comment by ctalkington** [comment]
given the `^0.2.1` in package. you should be able to clear npm cache and get any version just shy of 1.0.0 should they ever have one
